[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "avax"
node_type = "validator"
node_version = "1.9.2"
min_babel_version = "0.0.1"
description = "avax blockchain validator"
api_host = "http://localhost:9650/ext/bc/P/"

[firewall]
enabled = true
default_in = "deny"
default_out = "allow"

    [[firewall.rules]]
    name = "Allowed incoming traffic on port"
    action = "allow"
    direction = "in"
    ports = [9650]

[requirements]
vcpu_count = 8
mem_size_mb = 16384
disk_size_gb = 1000

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/avalanche/node"

    [[supervisor.entry_point]]
    name = "avalanchego-node"
    body = """
    test -f /blockjoy/.init && \
    avalanchego --version 
    """

[[methods]]
name = "height"
transport = "jrpc"
method = "platform.getHeight"

    [methods.response]
    code = 200
    field = "result.height"

[[methods]]
name = "address"
transport = "jrpc"
method = "platform.listAddresses" 

    [methods.response]
    code = 200
    field = "resut.addresses" 

[[methods]]
name = "status"
transport = "jrpc"
method = "platform.getBlockchainStatus"

    [methods.response]
    code = 200
    field = "result.status"
    # status_enum = { syncing = "Syncing", follower = "Created"}

[nets.mainnet]
net_type = "main"
url = "https://api.avax.network/ext/bc/C/rpc"

[nets.testnet]
net_type = "test"
url = "https://api.avax-test.network/ext/bc/C/rpc"
