[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "iris"
node_type = "validator"
node_version = "1.4.1"
min_babel_version = "0.0.1"
description = "iris blockchain validator"
api_host = "http://localhost:26657/"

[firewall]
enabled = true
default_in = "deny"
default_out = "allow"

    [[firewall.rules]]
    name = "Allowed incoming traffic on port"
    action = "allow"
    direction = "in"
    ports = [26657]

[requirements]
vcpu_count = 2
mem_size_mb = 6144
disk_size_gb = 256

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/iris"

    [[supervisor.entry_point]]
    name = "iris-node"
    body = """
    test -f /blockjoy/.init && \
    iris --home babelref:'supervisor.data_directory_mount_point' start
    """

[[methods]]
name = "init"
transport = "sh"
body = """
! test -f /blockjoy/.init && \
iris --home babelref:'supervisor.data_directory_mount_point' init --chain-id=babelref:'nets.{{NETWORK}}.chain_id' 2>&1 | logger -t babel.init && \
curl -o babelref:'supervisor.data_directory_mount_point'/config/config.toml https://raw.githubusercontent.com/irisnet/mainnet/master/config/config.toml 2>&1 | logger -t babel.init && \
curl -o babelref:'supervisor.data_directory_mount_point'/config/genesis.json https://raw.githubusercontent.com/irisnet/mainnet/master/config/genesis.json 2>&1 | logger -t babel.init && \
touch /blockjoy/.init
"""

    [methods.response]
    status = 200
    format = "raw"

[[methods]]
name = "application_status"
transport = "sh"
body = """
echo -n "Cancelled"
""" 

    [methods.response]
    status = 200
    format = "raw"

[[methods]]
name = "height"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "sync_info.latest_block_height"

[[methods]]
name = "address"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "validator_info.pub_key.value" 

[[methods]]
name = "status"
transport = "jrpc"
method = "health"

    [methods.response]
    code = 200
    field = "result"

[[methods]]
name = "genesis_info"
transport = "jrpc"
method = "genesis"

    [methods.response]
    code = 200
    field = "result"

[nets.mainnet]
net_type = "main"
url = "https://raw.githubusercontent.com/irisnet/mainnet/master/config/config.toml" # tbd
chain_id = "irishub-1"

[nets.testnet]
net_type = "test"
url = "https://github.com/irisnet/testnets/blob/master/nyancat/config/config.toml" # tbd
chain_id = ""
